{
  "uid" : "241d7bac88667645",
  "name" : "Browse acutesttraining PUBLICA‌-1 issue (should fail) -- @1.1 ",
  "historyId" : "fc86873a8b6e52f52d8247b533443e0e",
  "time" : {
    "start" : 1591194862171,
    "stop" : 1591194892178,
    "duration" : 30007
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 30.000\n  (Session info: chrome=83.0.4103.61)\n\n",
  "statusTrace" : "  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\jira_issue_steps.py\", line 14, in step_impl\n    context.issue_page.navigate(url)\n  File \"C:\\agent\\CDAFwin\\4\\s\\features\\pages\\issue_page.py\", line 18, in navigate\n    self.driver.get(address)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 30.000\n  (Session info: chrome=83.0.4103.61)\n\n",
    "statusTrace" : "  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\jira_issue_steps.py\", line 14, in step_impl\n    context.issue_page.navigate(url)\n  File \"C:\\agent\\CDAFwin\\4\\s\\features\\pages\\issue_page.py\", line 18, in navigate\n    self.driver.get(address)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Given the Jira Cloud instance acutesttraining has a publicly accessible project with issuekey \"PUBLICA‌-1\"",
      "time" : {
        "start" : 1591194862173,
        "stop" : 1591194862173,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false,
      "stepsCount" : 0
    }, {
      "name" : "When CDAF test visits the url \"https://acutesttraining.atlassian.net/browse/PUBLICA-1?oldIssueView=true\" without logging in",
      "time" : {
        "start" : 1591194862173,
        "stop" : 1591194892178,
        "duration" : 30005
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 30.000\n  (Session info: chrome=83.0.4103.61)\n\n",
      "statusTrace" : "  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\jira_issue_steps.py\", line 14, in step_impl\n    context.issue_page.navigate(url)\n  File \"C:\\agent\\CDAFwin\\4\\s\\features\\pages\\issue_page.py\", line 18, in navigate\n    self.driver.get(address)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\george-cooper\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true,
      "stepsCount" : 0
    }, {
      "name" : "Then the page title is \"Sample issue 20180615T1711\"",
      "time" : {
        "start" : 1591194892178,
        "stop" : 1591194892178,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false,
      "stepsCount" : 0
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true,
    "stepsCount" : 3
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "tag",
    "value" : "build-test"
  }, {
    "name" : "tag",
    "value" : "should-fail"
  }, {
    "name" : "tag",
    "value" : "web"
  }, {
    "name" : "feature",
    "value" : "Webdriver PUBLICA browser tests"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "issue",
    "value" : "Sample issue 20180615T1711"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "878138851f2de147",
      "status" : "passed",
      "time" : {
        "start" : 1590743336848,
        "stop" : 1590743339118,
        "duration" : 2270
      }
    }, {
      "uid" : "472e09a76bf6cc9e",
      "status" : "passed",
      "time" : {
        "start" : 1590682946818,
        "stop" : 1590682949237,
        "duration" : 2419
      }
    }, {
      "uid" : "89115cebf1f35b84",
      "status" : "passed",
      "time" : {
        "start" : 1590682796313,
        "stop" : 1590682798466,
        "duration" : 2153
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "build-test", "web", "should-fail" ]
  },
  "source" : "241d7bac88667645.json",
  "parameterValues" : [ "Sample issue 20180615T1711" ]
}